services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: ddre_tim
      POSTGRES_USER: ddre_tim
      POSTGRES_PASSWORD: ddre_tim
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: